const state={places:[],filtered:[],map:null,markers:[],favorites:JSON.parse(localStorage.getItem("klev-favorites")||"[]")};
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function saveFavorites(){localStorage.setItem("klev-favorites",JSON.stringify(state.favorites));$("favoriteCount").textContent=state.favorites.length}
function isFavorite(id){return state.favorites.includes(id)}
function toggleFavorite(id){state.favorites=isFavorite(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];saveFavorites();render()}
function filters(){return{fish:$("fish").value,distance:$("distance").value,method:$("method").value,search:$("search").value.trim().toLowerCase()}}
function applyFilters(){const f=filters();state.filtered=state.places.filter(p=>(f.fish==="all"||p.fish.includes(f.fish))&&(f.distance==="all"||p.distance<=Number(f.distance))&&(f.method==="all"||p.methods.includes(f.method))&&(`${p.name} ${p.description}`.toLowerCase().includes(f.search)));render()}
function render(){const data=state.filtered;$("resultCount").textContent=`${data.length} ${data.length===1?"место":"мест"}`;$("list").innerHTML=data.map(p=>`<article class="place-card"><div class="card-top"><h3>${escapeHtml(p.name)}</h3><span class="distance">${p.distance} км</span></div><div class="meta">${escapeHtml(p.region)} · ${escapeHtml(p.fish.join(" · "))}</div><p>${escapeHtml(p.description)}</p><div class="chips">${p.methods.map(m=>`<span class="chip">${escapeHtml(m)}</span>`).join("")}</div><div class="card-actions"><button class="small-button" onclick="focusPlace('${p.id}')">На карте ↗</button><button class="small-button secondary" onclick="openPlace('${p.id}')">Подробнее</button><button class="small-button ${isFavorite(p.id)?"saved":""}" onclick="toggleFavorite('${p.id}')">${isFavorite(p.id)?"★":"☆"}</button></div></article>`).join("")||"<p class='muted'>Ничего не найдено. Попробуй изменить фильтры.</p>";renderMarkers()}
function renderMarkers(){if(!state.map)return;state.markers.forEach(m=>state.map.geoObjects.remove(m));state.markers=state.filtered.map(p=>{const marker=new ymaps.Placemark([p.lat,p.lon],{hintContent:p.name,balloonContentHeader:`<b>${escapeHtml(p.name)}</b>`,balloonContentBody:`${escapeHtml(p.fish.join(", "))}<br>${escapeHtml(p.description)}`},{preset:"islands#blueFishingIcon"});state.map.geoObjects.add(marker);return marker})}
function focusPlace(id){const p=state.places.find(x=>x.id===id);if(!p||!state.map)return;state.map.setCenter([p.lat,p.lon],12,{duration:300});const marker=state.markers.find(m=>m.geometry.getCoordinates()[0]===p.lat&&m.geometry.getCoordinates()[1]===p.lon);if(marker)marker.balloon.open()}
function routePlace(id){const p=state.places.find(x=>x.id===id);if(p)window.open(`https://yandex.ru/maps/?rtext=~${p.lat},${p.lon}&rtt=auto`,"_blank")}
function openPlace(id){const p=state.places.find(x=>x.id===id);if(!p)return;$("dialogContent").innerHTML=`<div class="dialog-content"><p class="eyebrow">ВОДОЁМ</p><h2>${escapeHtml(p.name)}</h2><p>${escapeHtml(p.description)}</p><p><b>Рыба:</b> ${escapeHtml(p.fish.join(", "))}</p><p><b>Способы:</b> ${escapeHtml(p.methods.join(", "))}</p><p><b>Расстояние:</b> ${p.distance} км</p><p><b>Статус:</b> ${escapeHtml(p.status)}</p><div class="card-actions"><button class="small-button" onclick="focusPlace('${p.id}');$('placeDialog').close()">Показать на карте</button><button class="small-button secondary" onclick="routePlace('${p.id}')">Маршрут</button><button class="small-button ${isFavorite(p.id)?"saved":""}" onclick="toggleFavorite('${p.id}');openPlace('${p.id}')">${isFavorite(p.id)?"★ В избранном":"☆ В избранное"}</button></div></div>`;$("placeDialog").showModal()}
async function loadPlaces(){try{const response=await fetch("data/places.json");state.places=await response.json();state.filtered=[...state.places];$("resultCount").textContent=`${state.places.length} мест`;render()}catch(error){$("list").innerHTML="<p class='muted'>Не удалось загрузить данные мест.</p>"}}
function initMap(){if(!window.ymaps){$("map").innerHTML="<div class='map-loading'>Яндекс Карты не загрузились. Проверь API-ключ.</div>";return}ymaps.ready(()=>{state.map=new ymaps.Map("map",{center:[55.75,37.4],zoom:8,controls:["zoomControl","fullscreenControl"]});renderMarkers()})}
["fish","distance","method","search"].forEach(id=>$(id).addEventListener("input",applyFilters));
$("resetFilters").addEventListener("click",()=>{["fish","distance","method","search"].forEach(id=>$(id).value=id==="fish"||id==="method"?"all":"all");$("search").value="";applyFilters()});
$("favoritesToggle").addEventListener("click",()=>{state.filtered=state.places.filter(p=>isFavorite(p.id));render()});
$("closeDialog").addEventListener("click",()=>$("placeDialog").close());
saveFavorites();loadPlaces();initMap();
